(() => {
  "use strict";
  const page=location.pathname.split("/").pop()||"dashboard.html";
  const routes={Dashboard:"dashboard.html",Trades:"trades.html",Calendar:"calendar.html","Risk Management":"risk-management.html",Psychology:"psychology.html",Journal:"journal.html",Reports:"reports.html",Settings:"settings.html"};
  document.querySelectorAll(".nav-item[data-page]").forEach(node=>{const route=routes[node.dataset.page]||node.dataset.route;node.dataset.route=route||"";const active=route===page||(page==="ai-journal.html"&&route==="journal.html")||(["analytics.html","performance.html"].includes(page)&&route==="reports.html");node.classList.toggle("active",active);node.title=node.dataset.page||"";let tail=node.querySelector(".nav-tail");if(active&&!tail){tail=document.createElement("span");tail.className="nav-tail";tail.textContent="›";node.append(tail)}if(!active&&tail)tail.remove();node.addEventListener("click",()=>{if(route)location.href=route})});
  const body=document.body,sidebar=document.getElementById("sidebar"),collapse=document.getElementById("sidebarCollapseBtn"),menu=document.getElementById("mobileMenuBtn"),overlay=document.getElementById("sidebarOverlay");
  const saved=localStorage.getItem("protrade-sidebar-collapsed")==="1";if(saved&&innerWidth>980)body.classList.add("sidebar-collapsed");
  const updateCollapse=()=>{const is=body.classList.contains("sidebar-collapsed");if(collapse){collapse.textContent=is?"›":"‹";collapse.setAttribute("aria-label",is?"Expand sidebar":"Collapse sidebar");collapse.title=is?"Expand sidebar":"Collapse sidebar"}localStorage.setItem("protrade-sidebar-collapsed",is?"1":"0");setTimeout(()=>dispatchEvent(new Event("resize")),270)};updateCollapse();
  collapse?.addEventListener("click",e=>{e.stopPropagation();body.classList.toggle("sidebar-collapsed");body.classList.remove("sidebar-peek");updateCollapse()});
  let peekTimer;sidebar?.addEventListener("mouseenter",()=>{if(innerWidth>980&&body.classList.contains("sidebar-collapsed")){clearTimeout(peekTimer);body.classList.add("sidebar-peek")}});sidebar?.addEventListener("mouseleave",()=>{if(innerWidth>980&&body.classList.contains("sidebar-collapsed")){peekTimer=setTimeout(()=>body.classList.remove("sidebar-peek"),130)}});
  menu?.addEventListener("click",()=>body.classList.add("sidebar-open"));overlay?.addEventListener("click",()=>body.classList.remove("sidebar-open"));document.querySelectorAll(".nav-item").forEach(n=>n.addEventListener("click",()=>body.classList.remove("sidebar-open")));
  addEventListener("resize",()=>{if(innerWidth>980)body.classList.remove("sidebar-open");else body.classList.remove("sidebar-peek")});
  const theme=localStorage.getItem("protrade-theme")||localStorage.getItem("protrade_theme");if(theme){const s=theme.toLowerCase();document.documentElement.dataset.theme=s.includes("light")?"light":"dark"}
  // Keep labels/meta coherent after page-owned theme handlers execute.
  document.getElementById("themeSwitch")?.addEventListener("click",()=>setTimeout(()=>{const t=document.documentElement.dataset.theme==="light"?"light":"dark";localStorage.setItem("protrade-theme",t);["themeLabel","sidebarThemeLabel"].forEach(id=>{const n=document.getElementById(id);if(n)n.textContent=t==="dark"?"Dark Mode":"Light Mode"});document.querySelector('meta[name="theme-color"]')?.setAttribute("content",t==="dark"?"#06111f":"#f5f9fc")},40));
})();
